name: CI

on:
  schedule:
    - cron:  '30 5,17 * * *'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo " " >> README.md
        
      - uses: stefanzweifel/git-auto-commit-action@v4
