name: CI

on:
  schedule:
    - cron:  '30 5,17 * * *'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo " " >> README.md
      - name: Commit files and push it
        run: |
          git config --global user.email "eddieschaumanhaigh@icloud.com"
          git config --global user.name "EddieJLSH"
          git add .
          git commit -m "chore"
          git push
